#project/config/config.yml
aws:
  Tags:  # Add a Tags section here.. This will be used, eventually, for "global tags"
    Project: "YourProjectName"
    Environment: "Production"
    Owner: "YourName"
    AdditionalTag: "Value"
  #Update StackName to what you'd like as this is the CFT that deploys the VPC
  StackNameVPC: "PrivateAccess-VPC"
  StackNameEC2: "PrivateAccess-EC2"
  hosted_zone_id: "Z060647032UDOJ7WQIY6A" #AWS Route53 Hosted Zone ID #
  domain: "mydomain.com" #AWS Domain associated to the Hosted Zone
  portal_fqdn: "portal.domain.com"
  NamePrefix: "My-GP-" #NamePrefix for AWS Tag Name prefix. Alphanumeric and "-" only, must end with "-"
  Regions:
    # us-east-1:
    #   vpc_cidr: "10.22.240.0/23"
    #   key_name: "us-east1"
    #   ngfw_ami_id: "ami-0bda05a4d1a0eaf08"
    #   availability_zones:
    #       us-east-1-chi-2a: #the first AZ should be an AZ, not a local zone, if you are attaching TGW to the first subnet
    #         az_name: us-east-1-chi-2a #its just easier to do this
    #         NetworkBorderGroup: us-east-1-chi-2 #just enter the region/local zone
    #         instance_type: "m6i.xlarge"
    #         min_ec2_count: 1
    #         max_ec2_count: 3
    #         untrust_subnet_cidr: "10.22.240.0/28" #Untrust subnet
    #         trust_subnet_cidr: "10.22.240.16/28" #Trust subnet
    #         globalprotect:
    #           user_pool1: "10.0.0.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
    #           user_pool2: "10.0.2.0/23"
    #           user_pool3: "10.0.4.0/23"
    #           ebgp_as1: "64600"
    #           ebgp_as2: "64601"
    #           ebgp_as3: "64602"
    #       us-east-1-dfw-2a:
    #         az_name: us-east-1-dfw-2a #its just easier to do this
    #         NetworkBorderGroup: us-east-1-dfw-2 #just enter the region/local zone
    #         instance_type: "m6i.xlarge"
    #         min_ec2_count: 1
    #         max_ec2_count: 3
    #         untrust_subnet_cidr: "10.22.240.32/28" #Untrust subnet
    #         trust_subnet_cidr: "10.22.240.48/28" #Trust subnet
    #         globalprotect:
    #           user_pool1: "10.0.6.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
    #           user_pool2: "10.0.8.0/23"
    #           user_pool3: "10.0.10.0/23"
    #           ebgp_as1: "64603"
    #           ebgp_as2: "64604"
    #           ebgp_as3: "64605"
    #       us-east-1-atl-1a:
    #         az_name: us-east-1-atl-1a #its just easier to do this
    #         NetworkBorderGroup: us-east-1-atl-1 #just enter the region/local zone
    #         instance_type: "c5d.2xlarge"
    #         min_ec2_count: 1
    #         max_ec2_count: 3
    #         untrust_subnet_cidr: "10.22.241.0/28" #Untrust subnet
    #         trust_subnet_cidr: "10.22.241.16/28" #Trust subnet
    #         globalprotect:
    #           user_pool1: "10.0.160.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
    #           user_pool2: "10.0.180.0/23"
    #           user_pool3: "10.0.200.0/23"
    #           ebgp_as1: "64606"
    #           ebgp_as2: "64607"
    #           ebgp_as3: "64608"              
    us-east-2:
      vpc_cidr: "10.23.240.0/23"
      key_name: "us-east2"
      ngfw_ami_id: "ami-05c242756184e8330"
      availability_zones:
          us-east-2a:
            az_name: us-east-2a
            NetworkBorderGroup: us-east-2
            instance_type: "m6i.xlarge"
            min_ec2_count: 1
            max_ec2_count: 3
            untrust_subnet_cidr: "10.23.240.0/28" #Unrust subnet
            trust_subnet_cidr: "10.23.240.16/28" #Trust subnet
            tgw_id: tgw-0fd363e13bdb37843
            tgw_cidr: "10.1.120.0/24"
            globalprotect:
              user_pool1: "10.0.12.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
              user_pool2: "10.0.14.0/23"
              user_pool3: "10.0.16.0/23"
              ebgp_as1: "64609"
              ebgp_as2: "64610"
              ebgp_as3: "64611"
    # ap-south-1:
    #   vpc_cidr: "10.24.240.0/23"
    #   key_name: "ap-south-1"
    #   ngfw_ami_id: "ami-0e773f202f548fcee"
    #   availability_zones:
    #       ap-south-1a:
    #         az_name: ap-south-1a
    #         NetworkBorderGroup: ap-south-1
    #         instance_type: "m5.xlarge"
    #         min_ec2_count: 1
    #         max_ec2_count: 3
    #         untrust_subnet_cidr: "10.24.240.0/28" #Unrust subnet
    #         trust_subnet_cidr: "10.24.240.16/28" #Trust subnet
    #         tgw_id: tgw-0fd36234adf324
    #         tgw_cidr: "10.3.120.0/24"
    #         globalprotect:
    #           user_pool1: "10.0.18.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
    #           user_pool2: "10.0.20.0/23"
    #           user_pool3: "10.0.22.0/23"
    #           ebgp_as1: "64612"
    #           ebgp_as2: "64613"
    #           ebgp_as3: "64614"              
        # # Add more regions as needed

  EC2: # don't replace {} as these are variables to pull from palo_alto:panorama
    user_data: |
      type=dhcp-client
      hostname={NamePrefix}
      auth-key={panorama_auth_key}
      panorama-server={panorama_ip_address1}
      panorama-server-2={panorama_ip_address2}
      tplname={PanoramaTemplateStack}
      dgname={PanoramaDeviceGroup}
      plugin-op-commands=panorama-licensing-mode-on
      op-command-modes=jumbo-frame,mgmt-interface-swap
      op-cmd-dpdk-pkt-io=on
      cgname=default
      vm-series-auto-registration-pin-id=962e14cc-4305-4618-a63a-c33d3346c467
      vm-series-auto-registration-pin-value=312cd70318354d1e8d4472e96f16546a

palo_alto:
  panorama:
    ip_address1: 10.255.240.238
    ip_address2: 10.254.0.238
    auth_key: _AQ__2v6ck2zMRCMQugJDtfDzLeFrPP
    PanoramaTemplate: PPA-TPL
    PanoramaTemplateStack: PPA-TPL-Stack
    PanoramaDeviceGroup: PPA-DG
    OutsideVirtualRouter: "PPA-Untrust-VR"
    InsideVirtualRouter: "PPA-Trust-VR"
    UserZoneName: "VPN-Users"
    BranchZone: "Branch"
    LicenseManager: "PrivatePrismaLM" #license manager name used for sw_fw_license plugin in panorama
  ngfw:
    VirtualRouter: default
    BranchZone: "AWS"

vpn:
  crypto_settings:
    ike_crypto: 
      name: "IKE_Crypto"
      auth: "sha512"
      dh_group: "group19"
      encryption: "aes-256-cbc"
    ipsec_crypto: 
      name: "IPSEC_Crypto"
      auth: "none"
      dh_group: "group19"
      encryption: "aes-256-gcm"
    ike_gw: 
      psk: "EnterYourPSKHere!@$$"      
  on_prem_vpn_settings:
    site1:
      ike_peer_ip: "108.44.161.18"
      bgp_peer_ip: "169.254.10.1"
      as_number: "65000"
    site2:
      ike_peer_ip: "108.44.161.20"
      bgp_peer_ip: "169.254.10.2"
      as_number: "65000"

ebgp:
  routing_settings:
    PrivateAsRange: 64600-64630
    LoopBackCidr: 
    us-east-1:
      vpc_cidr: "10.22.240.0/23"
      key_name: "us-east1"
      ngfw_ami_id: "ami-0bda05a4d1a0eaf08"
      availability_zones:
          us-east-1-chi-2a: #the first AZ should be an AZ, not a local zone, if you are attaching TGW to the first subnet
            az_name: us-east-1-chi-2a #its just easier to do this
            NetworkBorderGroup: us-east-1-chi-2 #just enter the region/local zone
            instance_type: "m6i.xlarge"
            min_ec2_count: 1
            max_ec2_count: 3
            untrust_subnet_cidr: "10.22.240.0/28" #Untrust subnet
            trust_subnet_cidr: "10.22.240.16/28" #Trust subnet
            globalprotect:
              user_pool1: "10.0.0.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
              user_pool2: "10.0.2.0/23"
              user_pool3: "10.0.4.0/23"
              ebgp_as1: "64600"
              ebgp_as2: "64601"
              ebgp_as3: "64602"
          us-east-1-dfw-2a:
            az_name: us-east-1-dfw-2a #its just easier to do this
            NetworkBorderGroup: us-east-1-dfw-2 #just enter the region/local zone
            instance_type: "m6i.xlarge"
            min_ec2_count: 1
            max_ec2_count: 3
            untrust_subnet_cidr: "10.22.240.32/28" #Untrust subnet
            trust_subnet_cidr: "10.22.240.48/28" #Trust subnet
            globalprotect:
              user_pool1: "10.0.6.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
              user_pool2: "10.0.8.0/23"
              user_pool3: "10.0.10.0/23"
              ebgp_as1: "64603"
              ebgp_as2: "64604"
              ebgp_as3: "64605"
    us-east-2:
      vpc_cidr: "10.23.240.0/23"
      key_name: "us-east2"
      ngfw_ami_id: "ami-05c242756184e8330"
      availability_zones:
          us-east-2a:
            az_name: us-east-2a
            NetworkBorderGroup: us-east-2
            instance_type: "m6i.xlarge"
            min_ec2_count: 1
            max_ec2_count: 3
            untrust_subnet_cidr: "10.23.240.0/28" #Unrust subnet
            trust_subnet_cidr: "10.23.240.16/28" #Trust subnet
            tgw_id: tgw-0fd363e13bdb37843
            tgw_cidr: "10.1.120.0/24"
            globalprotect:
              user_pool1: "10.0.12.0/23" #update pool count based on min/max ec2 count. you can list more than max count, but don't list less than max
              user_pool2: "10.0.14.0/23"
              user_pool3: "10.0.16.0/23"
              ebgp_as1: "64609"
              ebgp_as2: "64610"
              ebgp_as3: "64611"
        # Add more regions as needed
  
  EC2:
    user_data: |
      type=dhcp-client
      hostname={NamePrefix}
      auth-key={panorama_auth_key}
      panorama-server={panorama_ip_address1}
      panorama-server-2={panorama_ip_address2}
      tplname={PanoramaTemplateStack}
      dgname={PanoramaDeviceGroup}
      plugin-op-commands=panorama-licensing-mode-on
      op-command-modes=jumbo-frame,mgmt-interface-swap
      op-cmd-dpdk-pkt-io=on
      vm-series-auto-registration-pin-id=962e14cc-4305-4618-a63a-c33d3346c467
      vm-series-auto-registration-pin-value=312cd70318354d1e8d4472e96f16546a


palo_alto:
  panorama:
    #update accordingly
    ip_address1: 10.254.0.237
    ip_address2: 10.254.0.238
    api_key: your-panorama-sw-fw-license-key
    PanoramaTemplate: PPA-TPL-Stack
    PanoramaDeviceGroup: PPA-DG
    VirtualRouter: "PPA-Trust-VR"
    UserZoneName: "VPN-Users"
    BranchZone: "Branch"
    LicenseManager: "PrivatePrismaLM" #license manager name used for sw_fw_license plugin in panorama
  ngfw:
    VirtualRouter: default
    BranchZone: "AWS"

vpn:
  crypto_settings:
    ike_crypto: 
      name: "IKE_Crypto"
      auth: "sha512"
      dh_group: "group19"
      encryption: "aes-256-cbc"
    ipsec_crypto: 
      name: "IPSEC_Crypto"
      auth: "none"
      dh_group: "group19"
      encryption: "aes-256-gcm"
    ike_gw: 
      psk: "YourPSKHERE3434$$#$#"      
  mesh_vpn_settings:
    # Settings for full mesh VPN configuration.. placeholder... will figure it out.
  on_prem_vpn_settings:
    site1:
      ike_peer_ip: "108.44.161.18"
      bgp_peer_ip: "169.254.10.1"
      as_number: "65000"
    site2:
      ike_peer_ip: "108.44.161.20"
      bgp_peer_ip: "169.254.10.2"
      as_number: "65000"

ebgp: # placeholder.. may find a way to use this versus manually defining for each region/zone
  routing_settings:
    PrivateAsRange: 64600-64630
    LoopBackCidr: 