aws:
  StackName: "PrivateAccess"
  NamePrefix: "PPA-"
  Regions:
    us-east-2:
      vpc_cidr: "10.18.240.0/23"
      subnet1_cidr_block: "10.18.240.0/26"
      subnet2_cidr_block: "10.18.240.64/26"
    us-west-1:
      vpc_cidr: "10.20.242.0/23"
      subnet1_cidr_block: "10.20.242.0/26"
      subnet2_cidr_block: "10.20.242.64/26"
    # Add more regions as needed
  # Add other global AWS settings here if needed

palo_alto:
  panorama:
    ip_address: "x.x.x.x"
    api_key: "your-panorama-api-key"
  ngfw_ami_id: "ami-xxxxxxxxxxxx"
  # Other Palo Alto specific configurations

vpn:
  mesh_vpn_settings:
    # Settings for full mesh VPN configuration

ibgp:
  routing_settings:
    # Settings for iBGP configuration