aws:
  #Update StackName to what you'd like as this is the CFT that deploys the VPC
  StackName: "PrivateAccess"
  #Update NamePrefix as all items will have this as its prefix for naming convention
  NamePrefix: "PPA-"
  Regions:
    us-east-2:
      #update accordingly
      vpc_cidr: "10.18.240.0/23"
      subnet1_cidr_block: "10.18.240.0/26"
      subnet2_cidr_block: "10.18.240.64/26"
      ngfw_ami_id: "ami-074413e137fc5826c"
      key_name: "us-east2"
    us-west-1:
      #update accordingly
      vpc_cidr: "10.20.242.0/23"
      subnet1_cidr_block: "10.20.242.0/26"
      subnet2_cidr_block: "10.20.242.64/26"
      ngfw_ami_id: "ami-01b6650ae9be2b4f9"
      key_name: "us-west1"
    # Add more regions as needed
  EC2:
    instance_type: "m5.xlarge"
    # Do not update items within {} as the ec2 script will pull from palo_alto:panorama
    user_data: |
      type=dhcp-client
      hostname={NamePrefix}
      auth-key={panorama_api_key}
      panorama-server={panorama_ip_address1}
      panorama-server-2={panorama_ip_address2}
      tplname={PanoramaTemplate}
      dgname={PanoramaDeviceGroup}
      plugin-op-commands=panorama-licensing-mode-on
      op-command-modes=jumbo-frame,mgmt-interface-swap
      op-cmd-dpdk-pkt-io=on

palo_alto:
  panorama:
    #update accordingly
    ip_address1: "10.254.0.237"
    ip_address2: "10.254.0.238"
    api_key: "your-panorama-api-key"
    PanoramaTemplate: "PPA-TPL-Stack"
    PanoramaDeviceGroup: "PPA-DG"

vpn:
  mesh_vpn_settings:
    # Settings for full mesh VPN configuration

ibgp:
  routing_settings:
    # Settings for iBGP configuration