palo_alto_ngfw_url: https://x.x.x.x/api/
palo_alto_password: xxxxxx
palo_alto_username: xxxxxx
palo_api_token: LUFRPT1tMlltKzFxamhTVnliTnN3Z1ZYS1JESk8yS2c9bUdERnl2bkk3ZzdVeGlGYkJRQXhZTmd1cE5GN2xTKzM3TTFlN3JlTmx1bDRmenhVMUtPWUE4WTZyVFJJNnV3Sg==